spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password:
  driver-class-name: com.mysql.jdbc.Driver

app:
  security:
    secret-key: ${SECRET-KEY}
    time-expiration: ${TIME-EXPIRATION}
